name: Publish release

on:
  release:
    types: [published]

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Publish with Gradle
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        NEW_VERSION=$(echo "${GITHUB_REF}" | cut -d "/" -f3)
        echo "New version: ${NEW_VERSION}"
        echo "Github username: ${GITHUB_ACTOR}"
        ./gradlew -Pversion=${NEW_VERSION} publish